
services:
  backend:
    build: ./backend
    container_name: scam_backend
    restart: always
    environment:
      DB_HOST: ${DB_HOST}  # Use RDS endpoint from .env
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${PORT}  # If you have a custom port for RDS
    ports:
      - "3000:3000"
    networks:
      - backend_network  # Optional: Add network for isolation

  frontend:
    build: ./frontend
    container_name: scam_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - backend_network  # Optional: Add network for isolation

volumes:
  mysql_data:

networks:
  backend_network:  # Create a custom network if desired for service isolation
    driver: bridge  # Optional: Can specify other network drivers (like overlay)
