version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: jobliers-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: scam_reports
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  jobliers-api:
    build: .
    container_name: jobliers-api
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: scam_reports
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["node", "server.js"]

volumes:
  mysql_data:
