version: '3.8'

services:
  database:
    build: ./database
    container_name: scam_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scam_reports
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql"
    # Only use MySQL for local development
    profiles:
      - dev

  backend:
    build: ./backend/jobliers-api
    container_name: scam_backend
    restart: always
    environment:
      DB_HOST: ${DB_HOST:-database}  # Uses 'database' for local, RDS for prod
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      DB_NAME: ${DB_NAME:-scam_reports}
    ports:
      - "3000:3000"
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: scam_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mysql_data:
