services: 
  #database:
  #  build: ./database
  #  container_name: scam_db
  #  restart: always
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #    MYSQL_DATABASE: scam_reports
  #    MYSQL_USER: admin
  #    MYSQL_PASSWORD: root
  #  ports:
  #    - "3306:3306"
  #  volumes:
  #    - mysql_data:/var/lib/mysql
  #  networks:
  #    - backend_network  # Optional: Add network for isolation

  backend:
    build: ./backend
    container_name: scam_backend
    restart: always
    environment:
      DB_HOST: ${DB_HOST}  # Use RDS endpoint in production or local database if dev
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - backend_network  # Optional: Add network for isolation

  frontend:
    build: ./frontend
    container_name: scam_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - backend_network  # Optional: Add network for isolation

volumes:
  mysql_data:

networks:
  backend_network:  # Create a custom network if desired for service isolation
    driver: bridge  # Optional: Can specify other network drivers (like overlay)
