services:
  database:
    image: mysql:latest  # Use official MySQL image
    container_name: scam_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-scam_reports}
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
    profiles:
      - dev

  backend:
    build: ./backend
    container_name: scam_backend
    restart: always
    environment:
      DB_HOST: ${DB_HOST:-database}
      DB_USER: ${DB_USER:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-root}
      DB_NAME: ${DB_NAME:-scam_reports}
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy  # Ensures database is ready
    profiles:
      - dev
      - prod

  frontend:
    build: ./frontend
    container_name: scam_frontend
    restart: always
    ports:
      - "8080:80"  # Adjust if needed
    depends_on:
      - backend
    profiles:
      - dev
      - prod

volumes:
  mysql_data: