services:
  backend:
    build: ./backend
    container_name: scam_backend
    restart: always
    environment:
      DB_HOST: ${DB_HOST}  # Use RDS endpoint from .env
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${MYSQL_PORT}
    ports:
      - "3306:3306"
    networks:
      - backend_network
    volumes:
      - backend_logs:/app/logs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: scam_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - backend_network

volumes:
  backend_logs:  # Stores backend logs

networks:
  backend_network:
    driver: bridge
