name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" | tr -d '' | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          set -e

          # Install system dependencies
          sudo yum update -y
          sudo yum install -y git docker

          # Start and enable Docker
          sudo service docker start
          sudo usermod -aG docker ec2-user

          # Install Docker Compose
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

          # Clone or pull project
          if [ ! -d "fightback" ]; then
            git clone https://github.com/YOUR_USERNAME/YOUR_REPO.git fightback
          fi

          cd fightback
          git pull origin main

          docker-compose down
          docker-compose up -d --build

          echo "Deployment complete."
          EOF

